// Generated by Elvynia
interface MousetrapStatic {
    bindGlobal(keyArray: string|string[], callback: (e: ExtendedKeyboardEvent, combo: string) => any, action?: string): void;
	unbindGlobal(keys: string|string[], action?: string): void;
}

interface MousetrapInstance {
    bindGlobal(keyArray: string|string[], callback: (e: ExtendedKeyboardEvent, combo: string) => any, action?: string): void;
	unbindGlobal(keys: string|string[], action?: string): void;
}